### ISSUE TITLE
Base Errors are not captured

### ISSUE THREAD

**Issue by iteratelance** [ntegral/nestjs-sentry#11]
When throwing an error that is other than, http, rpc, or ws no exception is captured. For example if I bootstrap the app and call a service, i.e. for a background task, per the docs https://docs.nestjs.com/standalone-applications

```js
const app = await NestFactory.create(AppModule);
app.get(MyService).doSomething();
```
Reviewing the code here https://github.com/ntegral/nestjs-sentry/blob/master/lib/services/sentry.interceptor.ts#L18 I see that there is case logic that has no fallback to handle ordinary node.js errors.  Again these errors might occur when services are called outside the context of an http request, like a background task so would be good to call captureException as a default https://github.com/ntegral/nestjs-sentry/blob/master/lib/services/sentry.interceptor.ts#L81 

Perhaps this is a limitation of NestJs interceptor error handling and regular Errors are not caught?

Side bar, and not related would be nice to have an AWSLambda integration that is compatible with your module or at least an option to flush immediately. As the default sentry plugin does not work on AWS because it must flush.
```js
Sentry.captureException(error);
Sentry.flush();
```

**Comment by ntegral** [comment]
These options have been added in the latest update version 1.0.5.  All of the base method implementations have been added to the service.  Before they were available and could only be accessed via the "client.instance().flush" etc. now once you instantiate the client you can access them directly "client.flush()" etc.
