### ISSUE TITLE
Sentry.init beforeSend option is not being executed

### ISSUE THREAD

**Issue by iteratelance** [ntegral/nestjs-sentry#12]
We have an app where we need the ability to manipulate payloads before being sent to sentry.  It doesn't appear that the beforeSend .init option is respected when instantiating via forRootAsync

```js
  Sentry.init({
    dsn: config.get('SENTRY_DSN'),
    environment: config.get('NODE_ENV'),
    beforeSend(event) {
      if (event.secret_info)) {
        delete event.secret_info;
      }
      return event;
    }
  });
```

**Comment by ntegral** [comment]
This has been updated in the latest version
