### ISSUE TITLE
The process exit before sending event to sentry

### ISSUE THREAD

**Issue by piotrekcyk** [ntegral/nestjs-sentry#19]
I don't see any events on my sentry dashboard.

My AppModule looks like follow (after 2 seconds when app started it generated a test exception):
![image](https://user-images.githubusercontent.com/17705520/99559455-1a366280-29c5-11eb-8a09-c4a213d27b64.png)

Dashboard still empty:
![image](https://user-images.githubusercontent.com/17705520/99559756-68e3fc80-29c5-11eb-9da5-52e684e37599.png)

But I think I have found a cause.
When I go to compiled code, and then comment line with `process.exit(1);` (https://github.com/ntegral/nestjs-sentry/blob/master/dist/services/sentry.service.js#L52) (on src code: https://github.com/ntegral/nestjs-sentry/blob/master/lib/services/sentry.service.ts#L35)

it started working. I saw event on dashboard:
![image](https://user-images.githubusercontent.com/17705520/99560423-22db6880-29c6-11eb-9dfb-49f9e803afab.png)

I have one conclusion, process was closed too fast, without waiting for succeed emitting event.
Any other idea?

**Comment by piotrekcyk** [comment]
Look this tip please: https://docs.sentry.io/platforms/node/configuration/draining/

**Comment by ntegral** [comment]
Please let me know if you have additional questions

**Comment by simplenotezy** [comment]
@ntegral Would love to see how to implement it using Nest.js. I am aware of the documentation, but unsure how the actual implementation in Nest.js looks like. Currently we've had:

```ts
import { Injectable, Logger, OnApplicationShutdown, OnModuleDestroy } from '@nestjs/common';
import * as Sentry from '@sentry/node';

@Injectable()
export class AppService implements OnApplicationShutdown, OnModuleDestroy {
  onModuleDestroy() {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    Sentry.close(2000).then(() => {
      process.exit();
    });
  }

  onApplicationShutdown(signal: string) {
    Logger.log(`Application is shutting down! Signal: ${signal}`); // e.g. "SIGINT"
  }
}
```

But does that suffice? E.g. provide enough time for app to properly shutdown and drain correctly?
