### ISSUE TITLE
Can you create a sample project where this is working?

### ISSUE THREAD

**Issue by chalettu** [ntegral/nestjs-sentry#21]
Tried to integrate this and ran into all sorts of issues based on the directions in the readme.  
LogLevel is not defined in your example syntax
Sentry.Severity.Log is not defined , definitely needs to be imported or maybe you can expose those constants from the Sentry SDK?  

Also, when trying to do the Async implementation I got errors about the return types for UseFactory method.  Would it be possible to have you create a simple example app that uses your library?  Thanks in advance

**Comment by ntegral** [comment]
I will look to create an example
