### ISSUE TITLE
@nestjs/graphql as an optional dependency

### ISSUE THREAD

**Issue by Gbuomprisco** [ntegral/nestjs-sentry#29]
Hi, as it's not a core module, would it be possible to remove @nestjs/graphql as a peerDependency or making it optional?

**Comment by ntegral** [comment]
This has been updated in the latest update...  It is a required module if you are using the interceptor.  May create a separate interceptor specifically for graphql??

**Comment by Gbuomprisco** [comment]
If it were me I would have created an additional module for graphql so that uses who are using REST won't need another dependency.

I have temporarily downgraded to the prior version to avoid pulling in another module.

I don't know if it's something you'll consider in the next version but there's my 2c

**Comment by ntegral** [comment]
The latest version has been updated to address packages that don't use or need graphql.
