### ISSUE TITLE
Feature request: implement `enabled` option

### ISSUE THREAD

**Issue by stvnyung** [ntegral/nestjs-sentry#3]
Hello there!

Thanks for the amazing package, we are using it right now and loving it !

I just have a small request, as of now, `@sentry/node` implements an option `enabled` which will indicate if sentry should report errors to the platform.

This will allow for quick disabling Sentry on dev environment for example.

If the request is approuve, I can work on a PR to implement this.

Thanks !

**Comment by ntegral** [comment]
Thanks for the feedback.  I'll look into this and get back to you

**Comment by ntegral** [comment]
Which configuration feature are you referring to: 
https://docs.sentry.io/error-reporting/configuration/?platform=javascript

**Comment by stvnyung** [comment]
Seems like I can't find it. Closing then. Thanks for your time

**Comment by Flambe** [comment]
It's not listed in their docs anywhere, but it is available on the options interface you pass to init.

https://github.com/getsentry/sentry-javascript/blob/master/packages/types/src/options.ts#L14
