### ISSUE TITLE
SentryInterceptor can not resolve dependencies

### ISSUE THREAD

**Issue by drdreo** [ntegral/nestjs-sentry#31]
Hey,
I have imported the `SentryInterceptor` and wanted to use it on my controllers.
```ts
import { SentryInterceptor } from '@ntegral/nestjs-sentry';


@UseInterceptors(SentryInterceptor)
@Controller()
export class MyController {}
```
Although, Sentry throws the following error:
```  
Nest can't resolve dependencies of the SentryInterceptor (SentryToken, ?). Please make sure that the argument Object at index [1] is available in the AppModule context
``` 

I have tried to put the SentryInterceptor as a provider, but no luck.

**Comment by ntegral** [comment]
This has been corrected in the latest version update

**Comment by otaviomad** [comment]
I seem to be having the same issue. I might be doing something wrong, so here's the code:
`
// app.module.ts
@Module({
  imports: [
    SentryModule.forRoot({
      dsn: process.env.SENTRY_DSN,
      debug: true,
      environment: process.env.APP_ENV,
      logLevel: LogLevel.Debug,
    }),
    AuthModule,
  ]
  controllers: [AppController],
  providers: [AppService, SentryService],
  exports: [SentryService],
})`
`
// auth.controller.ts
@UseInterceptors(SentryInterceptor)
@Controller('auth')
export class AuthController { ... }
`
it gives the following error:
`
Error: Nest can't resolve dependencies of the SentryInterceptor (?). Please make sure that the argument Object at index [0] is available in the AuthModule context.
`
Am I doing something wrong? Not sure what to do, already added the service to the providers and exports.

**Comment by boy51** [comment]
This is still a problem in 2.x

**Comment by ntegral** [comment]
I'll review this issue. Thx

**Comment by boy51** [comment]
I made repro: https://github.com/boy51/ntegral-nest-sentry-error-repo/blob/main/src/app.module.ts

I tried to fix it but I couldn't find anything in PRs. If you can point me in the right direction i can try to make a pr
