### ISSUE TITLE
Filter http exceptions

### ISSUE THREAD

**Issue by wodka** [ntegral/nestjs-sentry#35]
It would be nice to exclude certain exception types. Is there a way to do this?

**Comment by ntegral** [comment]
the sentryinterceptor will accept filter options, please refer to the options param: it expects: SentryInterceptorOptions.. thanks

**Comment by wodka** [comment]
As there is no documentation around it:

what does the `type: any` do on the SentryInterceptorOptionsFilter?

right now I would assume that this would work like:
```
{
  filters: [
    {
      filter: (e) => e.statusCode === 404
    }
  ]
}
```

but then - as asked - what does the type do?

**Comment by wodka** [comment]
ok, based on what I saw in the code it should be usable like this:

```
{
  filters: [
    {
      type: HttpException,
      filter: (e) => e.statusCode === 404 // this is then optional
    }
  ]
}
```
