### ISSUE TITLE
Sentry module does't capture errors

### ISSUE THREAD

**Issue by serjo96** [ntegral/nestjs-sentry#37]
I imported to my app module 

``` 
SentryModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (cfg: ConfigService) => ({
        dsn: cfg.sentryDns,
        debug: true,
        enabled: true,
        environment: cfg.nodeEnv,
        tracesSampleRate: 1.0,
        release: cfg.version
      }),
      inject: [ConfigService],
    })
```

**"@ntegral/nestjs-sentry": "2.0.6",
"@sentry/node": "6.2.3",**

And also try add in main.ts app.useGlobalInterceptors(new SentryInterceptor()).

But any exption doesen’t  catch  in sentry. 
Erorrs catch if I init sentry in main.ts and throw error in mian.ts bootsrap function after init sentry;

If I try to add to app controller `@UseInterceptors(new SentryInterceptor())`
Its catch only like that, how I understand sentry must by default catch any 500 errors and upper.

**Comment by ntegral** [comment]
I'll see if I can reproduce this error. Thanks

**Comment by Amethystafyy282** [comment]
Any update on this one, i've had the same situation :D
