### ISSUE TITLE
Typo in Graphql Interceptor

### ISSUE THREAD

**Issue by wodka** [ntegral/nestjs-sentry#43]
with the commit https://github.com/ntegral/nestjs-sentry/commit/2dbdd79f601c5e1beedbd5243d282b1468a81dbd there seems to be a type for the import:

```
({ GqlExecutionContxt } = require('@nestjs/graphql'));
```

instead of GqlExecutionContxt I think it should be GqlExecutionContext

**Comment by msimon** [comment]
I had the same issue. Fixed it with this PR:
https://github.com/ntegral/nestjs-sentry/pull/44

**Comment by ltudisco** [comment]
Oh just stumbled into this bug as well!

**Comment by msimon** [comment]
I ended up using nest-raven. The library is way better documented and works very well.

**Comment by ntegral** [comment]
This will be updated in version 2.0.8
