### ISSUE TITLE
Missing peer dependency on @sentry/types

### ISSUE THREAD

**Issue by holm** [ntegral/nestjs-sentry#46]
I believe a peer dependency is missing in `package.json`, as `@sentry/types` is used at https://github.com/ntegral/nestjs-sentry/blob/master/lib/sentry.interfaces.ts#L2, but not listed as a peer dependency.

**Comment by ntegral** [comment]
@sentry/types is installed with the npm i @sentry/node --save

**Comment by holm** [comment]
Alright, thanks
