### ISSUE TITLE
nestjs-sentry 2.0.7 is not compatible with NestJS 8

### ISSUE THREAD

**Issue by kbzowski** [ntegral/nestjs-sentry#47]
SentryModule causes freeze during app bootstrapping.

**Comment by darinrogers** [comment]
Just for some more context, here's my error:
`
node_modules/@ntegral/nestjs-sentry/dist/sentry.service.d.ts:4:22 - error TS2415: Class 'SentryService' incorrectly extends base class 'Logger'.
  Property 'options' is private in type 'SentryService' but not in type 'Logger'.

4 export declare class SentryService extends Logger {
  `

**Comment by Kronhyx** [comment]
## Migration guide

https://docs.nestjs.com/migration-guide#logger-breaking-changes

**Comment by ntegral** [comment]
@Kronhyx, @darinrogers, @kbzowski - v3.0.0 will support NestJS 8 since there are breaking changes between version 7 and 8

**Comment by Kronhyx** [comment]
@ntegral some ETA of when version 3.x.y will be released?

**Comment by spasecadet** [comment]
@ntegral pinging on the ETA for v3, thanks!

**Comment by ntegral** [comment]
@kbzowski , @Kronhyx, @darinrogers, @spasecadet: Version 3.x.x with NestJS 8 support has been released!! Thx for your support!!
