### ISSUE TITLE
node_modules/@ntegral/nestjs-sentry/dist/sentry.service.d.ts:1:10 - error TS2305: Module '"@nestjs/common"' has no exported member 'ConsoleLogger'.

### ISSUE THREAD

**Issue by g-hostsolutions** [ntegral/nestjs-sentry#48]
after install and configure like this:

imports: [
    SentryModule.forRoot({
      dsn: 'sentry_io_dsn',
      debug: true | false,
      environment: 'dev' | 'production' | 'some_environment',
      release: 'some_release', | null, // must create a release in sentry.io dashboard
      logLevel: LogLevel.Debug //based on sentry.io loglevel //
    }),
  ],

Obs: i change the values to my need...

return 2 errors:

node_modules/@ntegral/nestjs-sentry/dist/sentry.interfaces.d.ts:4:10 - error TS2305: Module '"@nestjs/common"' has no exported member 'ConsoleLoggerOptions'.

and 

node_modules/@ntegral/nestjs-sentry/dist/sentry.service.d.ts:1:10 - error TS2305: Module '"@nestjs/common"' has no exported member 'ConsoleLogger'.

**Comment by robinjanke** [comment]
Hey @g-hostsolutions, how did you managed to fix that?

**Comment by caseychoiniere** [comment]
@robinjanke This is most likely related to a breaking change in NestJS version 8
https://docs.nestjs.com/migration-guide#logger-breaking-changes
