### ISSUE TITLE
"log" is not a valid value of the "level" parameter when capturing messages

### ISSUE THREAD

**Issue by ShaneRich5** [ntegral/nestjs-sentry#6]
All the application logs with an invalid `level` value of `log` are sent to Sentry.

The available log levels, https://docs.sentry.io/platforms/javascript/#setting-the-level

Example of an invalid log event:
![image](https://user-images.githubusercontent.com/6422774/79024027-be168080-7b4f-11ea-9c9e-79d73df1298f.png)

**Comment by ntegral** [comment]
I will review this issue. Thanks

**Comment by ntegral** [comment]
Are you still getting this error?

**Comment by ShaneRich5** [comment]
Yup

**Comment by ntegral** [comment]
Do you have @sentry/node installed in your project?

npm i --save @sentry/node

I was not able to replicate your error?
