### ISSUE TITLE
Question - Globally enable sentry in whole app without adding interceptor or injectables

### ISSUE THREAD

**Issue by abhimanusharma** [ntegral/nestjs-sentry#62]
I am already using sentry with ReactJs and it is working great with my project. All errors are logging in Sentry dashboard globally without doing anything special or any 3rd party logging in entire application manually.

I am trying to implement the same feature globally by just adding the package's settings in AppModule,

```
SentryModule.forRoot({
		dsn: envConfig.SENTRY_DSN,
		debug: true,
		environment: currentEnv,
		release: null, // must create a release in sentry.io dashboard
		logLevel: LogLevel.Debug //based on sentry.io loglevel 
}),
```

This is not working properly even when all settings are correct.

**Comment by MatthewHerbst** [comment]
@meirka did you figure this out?

@ntegral the goal here is to enable Sentry across the entire app without having to inject it into every injectable.

**Comment by meirka** [comment]
@ntegral thank you!
