### ISSUE TITLE
How to use this in middleware?

### ISSUE THREAD

**Issue by deli-gajigesa** [ntegral/nestjs-sentry#64]
Currently I have middleware that read `X-Request-ID` header passed to our nestjs service or generate a new one if it's not found, I want to set `request_id` tag in Sentry, but how can I expose this into the middleware?

The code from Sentry docs sample
```typescript
Sentry.configureScope((scope) => {
  scope.setTag("request_id", requestId);
});
```

**Comment by yldrmzffr** [comment]
Can you share the code parts here?
