### ISSUE TITLE
Relax dependency on nestjs-common 7.x

### ISSUE THREAD

**Issue by olivierlacan** [ntegral/nestjs-sentry#7]
Curious if there's anything specific holding you back from loosening the dependency on `@nestjs/common`. It's currently pinned to `6.11.8`. `7.0.0` was [released on March 17th](https://github.com/nestjs/nest/releases/tag/v7.0.0) so it should be fairly stable by now. 

Deprecations are listed here: https://docs.nestjs.com/migration-guide

I can submit a PR if you think this is feasible and welcome.

**Comment by patrickmichalina** [comment]
Any plan to bump this?

**Comment by SirMishaa** [comment]
It would be nice. 

Up

**Comment by ntegral** [comment]
This updated has been pushed in the latest version. Thanks
